version: '2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always

  conveyor:
    image: shad0wsong/conveyor:latest
    restart: always
    environment:
      - SERVER_PORT=8080
    links:
      - deal
    ports:
      - "8080:8080"

  deal:
    image: shad0wsong/deal:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=5000
    links:
      - db
      - conveyor
      - gateway
      - kafka
    ports:
      - "5000:5000"

  applicationms:
    image: shad0wsong/applicationms:latest
      restart: always
      environment:
        - SERVER_PORT=8555
      links:
        -gateway
        -deal
      ports:
        - "8555:8555"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  dossier:
    image: shad0wsong/dossier:latest
      restart: always
      environment:
        - SERVER_PORT=8500
      links:
        -kafka
      ports:
        - "8500:8500"

  gateway:
    image: shad0wsong/gateway:latest
      restart: always
      environment:
        - SERVER_PORT=6000
      links:
        -deal
        -applicationms
      ports:
        - "6000:6000"
